_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    de: de
    bn: bn
    hi: hi
    es: es
  domains:
    en: en
    de: de
    bn: ''
    hi: ''
    es: ''
selected_langcode: site_default
