1:
  id:
    value: '1'
  uuid:
    value: 5dc4be97-0f86-4e0e-b908-322da90292ce
  revision_id:
    value: '1'
  langcode:
    value: en
  bundle:
    value: menu_link_content
  revision_created:
    value: '1718795437'
  revision_user: false
  revision_log_message: false
  enabled:
    value: '1'
  title:
    value: Home
  description: false
  menu_name:
    value: custom-menu
  link:
    uri: 'entity:node/3'
    title: ''
    options: {  }
  external:
    value: '0'
  rediscover:
    value: '0'
  weight:
    value: '-49'
  expanded:
    value: '0'
  parent: false
  changed:
    value: '1718795791'
  default_langcode:
    value: '1'
  revision_default:
    value: '1'
  revision_translation_affected:
    value: '1'
2:
  id:
    value: '2'
  uuid:
    value: 73584fdc-5b20-48e8-a694-1ae4f53ccd14
  revision_id:
    value: '2'
  langcode:
    value: en
  bundle:
    value: menu_link_content
  revision_created:
    value: '1718795667'
  revision_user: false
  revision_log_message: false
  enabled:
    value: '1'
  title:
    value: 'Generic News'
  description: false
  menu_name:
    value: custom-menu
  link:
    uri: 'entity:node/5'
    title: ''
    options: {  }
  external:
    value: '0'
  rediscover:
    value: '0'
  weight:
    value: '-50'
  expanded:
    value: '0'
  parent: false
  changed:
    value: '1718796176'
  default_langcode:
    value: '1'
  revision_default:
    value: '1'
  revision_translation_affected:
    value: '1'
3:
  id:
    value: '3'
  uuid:
    value: 733d2ef2-ca67-42b3-98d7-d30e5e6f7d4f
  revision_id:
    value: '3'
  langcode:
    value: en
  bundle:
    value: menu_link_content
  revision_created:
    value: '1718795757'
  revision_user: false
  revision_log_message: false
  enabled:
    value: '1'
  title:
    value: Sports
  description: false
  menu_name:
    value: custom-menu
  link:
    uri: 'entity:node/6'
    title: ''
    options: {  }
  external:
    value: '0'
  rediscover:
    value: '0'
  weight:
    value: '-50'
  expanded:
    value: '0'
  parent:
    value: 'menu_link_content:73584fdc-5b20-48e8-a694-1ae4f53ccd14'
  changed:
    value: '1718795791'
  default_langcode:
    value: '1'
  revision_default:
    value: '1'
  revision_translation_affected:
    value: '1'
