_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 26ba73f3-2b33-4fc7-8003-7df47ccd98ef
name: 'Drupal Training'
mail: dptest.life@drupaltraining.com
slogan: 'The best place to understand Drupal concepts!'
page:
  403: /node/2
  404: /node/1
  front: /node/3
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
